name: Foundry Release

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'
    paths:
      - 'version.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: | 
          VER=$(cat version.txt)
          echo "VERSION=$VER" >> $GITHUB_ENV
      
      # Substitute the Manifest and Download URLs in the module.json
      - name: Substitute Manifest and Download Links For Versioned Ones
        id: sub_manifest_link_version
        uses: microsoft/variable-substitution@v1
        with:
          files: 'module.json'
        env:
          version: ${{ env.VERSION }}
          url: https://github.com/${{github.repository}}
          manifest: https://github.com/${{github.repository}}/releases/latest/download/module.json
          download: https://github.com/${{github.repository}}/releases/download/${{ env.VERSION }}/module.zip

      # Create a zip file with all files required by the module to add to the release
      - run: zip -r ./module.zip module.json LICENSE README.md scripts/

      # Create a release for this specific version
      - name: Update Release with Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true # Set this to false if you want to prevent updating existing releases
          name: ${{ github.event.release.name }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './module.json, ./module.zip'
          tag: ${{ env.VERSION }}
          body: ${{ github.event.release.body }}
